# Generated by Django 5.2.4 on 2025-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gorilla_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('card_type', models.TextField(blank=True, null=True)),
                ('annual_fee', models.TextField(blank=True, null=True)),
                ('min_spending', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('local_image_path', models.TextField(blank=True, null=True)),
                ('benefits_summary', models.TextField(blank=True, null=True)),
                ('benefits_json', models.TextField(blank=True, null=True)),
                ('structured_benefit', models.TextField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
    ]
