# Generated by Django 5.2.4 on 2025-12-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_alter_financialcompany_cal_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_products',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='products.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='saving_products',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='products.savingproducts'),
        ),
    ]
