# Generated by Django 5.2.4 on 2025-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deposit_products_user_saving_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='greeting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
