# Generated by Django 5.2.4 on 2025-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='dcls_month',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='dcls_month',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
