# Generated by Django 5.2.4 on 2025-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depositproducts_dcls_month_savingproducts_dcls_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(blank=True, default='', max_length=6)),
                ('fin_co_no', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('dcls_chrg_man', models.CharField(blank=True, default='', max_length=100)),
                ('homp_url', models.URLField(blank=True, default='', max_length=500)),
                ('cal_tel', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
