# Generated by Django 5.2.4 on 2025-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_financialcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcompany',
            name='cal_tel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialcompany',
            name='dcls_chrg_man',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialcompany',
            name='homp_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialcompany',
            name='kor_co_nm',
            field=models.CharField(max_length=200),
        ),
    ]
