# Generated by Django 5.2.4 on 2025-12-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_remove_card_primary_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBenefitIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('benefit_type', models.CharField(blank=True, default='', max_length=20)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('amount_won', models.IntegerField(blank=True, null=True)),
                ('limit_month_won', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_index', to='cards.card')),
            ],
            options={
                'indexes': [models.Index(fields=['card', 'category'], name='recommend_c_card_id_780dfb_idx'), models.Index(fields=['category'], name='recommend_c_categor_65c36d_idx')],
            },
        ),
    ]
