# Generated by Django 5.2.4 on 2025-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardbenefitindex',
            name='recommend_c_card_id_780dfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardbenefitindex',
            name='recommend_c_categor_65c36d_idx',
        ),
        migrations.RemoveField(
            model_name='cardbenefitindex',
            name='card',
        ),
        migrations.AddField(
            model_name='cardbenefitindex',
            name='source_card_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardbenefitindex',
            name='benefit_type',
            field=models.CharField(blank=True, default='PERCENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardbenefitindex',
            name='category',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='cardbenefitindex',
            index=models.Index(fields=['source_card_id', 'category'], name='recommend_c_source__8e700c_idx'),
        ),
    ]
