# Generated by Django 5.2.4 on 2025-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_remove_cardbenefitindex_recommend_c_card_id_780dfb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbenefitindex',
            name='brand',
            field=models.CharField(blank=True, default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='cardbenefitindex',
            name='cond_min_spending',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardbenefitindex',
            name='raw_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
