# Generated by Django 5.2.4 on 2025-12-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_is_lobby_alter_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='dm_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
    ]
