# Generated by Django 5.2.4 on 2025-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatroom_dm_key_chatroom_is_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
