# Generated by Django 5.2.4 on 2025-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatroom_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
