# Generated by Django 5.2.4 on 2025-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorilla_id', models.IntegerField(help_text='카드고릴라 고유 ID', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('credit', '신용카드'), ('check', '체크카드')], default='credit', max_length=20)),
                ('annual_fee', models.CharField(blank=True, help_text='연회비 정보', max_length=200)),
                ('min_spending', models.IntegerField(default=0, help_text='전월실적 조건(원)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('benefits_summary', models.TextField(blank=True, help_text='혜택 요약 텍스트')),
                ('benefits_json', models.JSONField(default=list, help_text='원본 혜택 JSON')),
                ('structured_benefit', models.JSONField(default=list, help_text='정규화된 혜택 JSON')),
                ('ranking', models.IntegerField(blank=True, help_text='인기 순위', null=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ranking', '-created_at'],
                'indexes': [models.Index(fields=['ranking'], name='cards_card_ranking_50282b_idx'), models.Index(fields=['company'], name='cards_card_company_97bc5d_idx'), models.Index(fields=['card_type'], name='cards_card_card_ty_f28ef4_idx')],
            },
        ),
    ]
