# Generated by Django 5.2.4 on 2025-12-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='local_image_path',
        ),
    ]
