# Generated by Django 5.2.4 on 2025-12-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_local_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_url',
        ),
    ]
