# Generated by Django 5.2.4 on 2025-12-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEmbeddingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(help_text='Chroma document ID', max_length=100, unique=True)),
                ('embedding_version', models.IntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, help_text='임베딩 텍스트 해시', max_length=64)),
                ('needs_embedding', models.BooleanField(db_index=True, default=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('query_text', models.TextField(blank=True, help_text='자연어 질의')),
                ('filters', models.JSONField(default=dict, help_text='적용된 필터')),
                ('result_card_ids', models.JSONField(default=list, help_text='추천 결과 카드 ID 목록')),
                ('result_scores', models.JSONField(default=list, help_text='추천 점수 목록')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='처리 시간(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', '조회'), ('CLICK', '클릭'), ('LIKE', '좋아요'), ('APPLY', '신청')], max_length=10)),
                ('context', models.JSONField(default=dict, help_text='추가 컨텍스트 (화면, 쿼리 등)')),
                ('session_id', models.CharField(blank=True, help_text='비로그인 사용자 세션', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spend', models.IntegerField(default=0, help_text='월 평균 소비 금액(원)')),
                ('category_weights', models.JSONField(default=dict, help_text="카테고리별 선호 가중치 {'COFFEE': 3, 'FOOD': 2, ...}")),
                ('fee_tolerance', models.IntegerField(default=0, help_text='연회비 허용 상한(원)')),
                ('min_spend_tolerance', models.IntegerField(default=0, help_text='전월실적 허용 상한(원)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='annual_fee_min',
            field=models.IntegerField(default=0, help_text='최소 연회비(원) - 필터용'),
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.JSONField(default=list, help_text='모든 혜택 카테고리 목록'),
        ),
        migrations.AddField(
            model_name='card',
            name='primary_category',
            field=models.CharField(choices=[('TRANS', '교통'), ('COMM', '통신'), ('SHOP', '쇼핑'), ('COFFEE', '카페'), ('FOOD', '외식'), ('GAS', '주유'), ('UTIL', '공과금'), ('SUB', '구독'), ('PAY', '페이'), ('TRAVEL', '여행'), ('MART', '마트'), ('ETC', '기타')], db_index=True, default='ETC', help_text='대표 카테고리 코드', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CRD', '신용카드'), ('CHK', '체크카드')], default='CRD', max_length=20),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['min_spending'], name='cards_card_min_spe_138b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['annual_fee_min'], name='cards_card_annual__3fe236_idx'),
        ),
        migrations.AddField(
            model_name='cardembeddingstate',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_state', to='cards.card'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cards.card'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cardembeddingstate',
            index=models.Index(fields=['needs_embedding'], name='cards_carde_needs_e_618ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='cardembeddingstate',
            index=models.Index(fields=['embedding_version'], name='cards_carde_embeddi_73115f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'created_at'], name='cards_recom_user_id_e928f1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['created_at'], name='cards_recom_created_21b624_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'created_at'], name='cards_usere_user_id_2aff84_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['card', 'created_at'], name='cards_usere_card_id_95e2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', 'created_at'], name='cards_usere_event_t_4dfda0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='cards_userp_user_id_83a716_idx'),
        ),
    ]
