# Generated by Django 5.2.4 on 2025-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('CRD', '신용카드'), ('CHK', '체크카드')], default='CRD', max_length=20),
        ),
    ]
