# Generated by Django 5.2.4 on 2025-12-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_add_recommendation_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='primary_category',
        ),
    ]
