# Generated by Django 5.2.4 on 2025-12-23 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_create_missing_userprofiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['card', 'event_type'], name='cards_usere_card_id_926864_idx'),
        ),
        migrations.AddConstraint(
            model_name='userevent',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'card', 'event_type'), name='unique_user_card_event'),
        ),
    ]
